CREATE TABLE `plot` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ll_x` decimal(9,6) NOT NULL,
  `ll_y` decimal(9,6) NOT NULL,
  `ur_x` decimal(9,6) NOT NULL,
  `ur_y` decimal(9,6) NOT NULL,
  `polygon` varchar(150) NOT NULL,
  `user_id` int(11) NOT NULL,
  `title` varchar(45) NOT NULL,
  `description` varchar(150) NOT NULL,
  `address1` varchar(45) NOT NULL,
  `address2` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `country` varchar(45) NOT NULL,
  `power` tinyint(1) NOT NULL DEFAULT '0',
  `water` tinyint(1) NOT NULL DEFAULT '0',
  `gas` tinyint(1) NOT NULL DEFAULT '0',
  `sewer` tinyint(1) NOT NULL DEFAULT '0',
  `internet` tinyint(1) NOT NULL DEFAULT '0',
  `garage` tinyint(1) NOT NULL DEFAULT '0',
  `price` int(11) NOT NULL,
  `currency` varchar(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `my_foreign_key_user_idx` (`user_id`),
  CONSTRAINT `my_foreign_key_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1