CREATE TABLE `plot` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ll_x` decimal(9,6) NOT NULL,
  `ll_y` decimal(9,6) NOT NULL,
  `ur_x` decimal(9,6) NOT NULL,
  `ur_y` decimal(9,6) NOT NULL,
  `polygon` varchar(150) NOT NULL,
  `user_id` int(11) NOT NULL,
  `title` varchar(45) NOT NULL,
  `description` text NOT NULL,
  `address1` varchar(45) NOT NULL,
  `address2` varchar(45) DEFAULT NULL,
  `district` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `country` varchar(45) NOT NULL,
  `price` int(11) NOT NULL,
  `currency` varchar(3) NOT NULL,
  `size` int(3) NOT NULL,
  `added` date NOT NULL,
  `expires` date NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `my_foreign_key_user_idx` (`user_id`),
  KEY `ll_x_index` (`ll_x`),
  KEY `ll_y_index` (`ll_y`),
  KEY `ur_x_index` (`ur_x`),
  KEY `ur_y_index` (`ur_y`),
  KEY `PriceIndex` (`price`),
  KEY `SizeIndex` (`size`),
  KEY `CityIndex` (`city`),
  KEY `DistrictIndex` (`district`),
  CONSTRAINT `my_foreign_key_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;